site_name: "Sua Disciplina - UNA"
site_url: https://danhpaiva.github.io/una-uc-mkdocs-template/
site_author: Daniel Paiva

theme:
  name: material
  language: pt-BR
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.sections

nav:
  - Home: index.md
  - Guia de In√≠cio: setup.md

plugins:
  - search
  - mkdocs-git-revision-date-localized-plugin:
      locale: pt_BR
      type: timeago
