site_name: "Sua Disciplina - UNA"
site_url: https://danhpaiva.github.io/una-uc-mkdocs-template/
site_author: Daniel Paiva

theme:
  name: material
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.sections
    - navigation.expand # Deixa o menu lateral aberto por padr칚o
    - navigation.top # Bot칚o "Voltar ao topo" autom치tico
    - navigation.tracking # Atualiza a URL conforme o aluno rola a p치gina
    - content.code.copy # Bot칚o de copiar c칩digo em um clique

nav:
  - Home: index.md
  - Guia do Professor: setup.md
  - 游닀 Aulas:
      - Introdu칞칚o: aulas/01-introducao.md
  - 游닇 Atividades:
      - Projeto 01: trabalhos/projeto-01.md

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
# Para habilitar estat칤sticas, crie um ID no Google Analytics e preencha abaixo:
# extra:
#   analytics:
#     provider: google
#     property: !ENV [GA_ID, "G-XXXXXXXXXX"] # Busca nas vari치veis de ambiente ou usa o padr칚o
